# Site settings
title: 박주영의 위키
url: "https://jxmen.github.io"
baseurl: ""
# description: >
#     박주영의 위키

# My information
email: me@jxmen.dev
author: 박주영
profile: 박주영
github_username: jxmen
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-spaceship

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: jxmen/jxmen.github.io
  repo_id: R_kgDOLKyoHA
  category: Comments
  category_id: DIC_kwDOLKyoHM4CdGSe

# google_analytics:
#   ua: SAMPLE-VALUE
#   encrypted_ua: THIS-IS-SAMPLE-VALUE

# google_adsense:
#   client: SAMPLE-VALUE

blame: "https://github.com/jxmen/jxmen.github.io/blame/main/_wiki"
edit: "https://github.com/jxmen/jxmen.github.io/edit/main/_wiki"
issue: "https://github.com/jxmen/jxmen.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
